wit: add more keywords to the escape list
bytecodealliance/wasm-tools-go pull request #159
Opened 2024-09-08 05:35 UTC by Mossaka

while i am trying to add more runtime tests from the wit-bindgen repo to here, I discovered that there are a lot of words such as `bool` are not being covered. I also found the package names are not being escaped.

This commit fixes both issues

2024-09-08 21:07 UTC, ydnar requested changes
Thanks! This is great. 

Can you split into two PRs: one that makes the changes (with small test changes as necessary) and a second PR that introduces the large number of new test files?

2024-09-08 21:07 UTC, ydnar commented on wit/ident.go
>  	id.Namespace, id.Package, _ = strings.Cut(base, ":")
I'd put these into temp vars stage then mutate id twice.

2024-09-08 21:07 UTC, ydnar commented on wit/wit.go
> +		// constructor is a keyword in WIT, but should not be escaped as a function name
👍

2024-09-09 05:04 UTC, Mossaka commented
> Can you split into two PRs: one that makes the changes (with small test changes as necessary) and a second PR that introduces the large number of new test files?

This PR only adds 4 test files. Are you suggesting to trim down the test files further?

2024-09-13 05:01 UTC, ydnar commented
@Mossaka your PR uncovered some interesting bugs, thanks!

2024-09-13 06:05 UTC, ydnar requested changes
Need to update CHANGELOG, but that’s it!

2024-09-13 06:53 UTC, Mossaka commented
Done

2024-09-13 14:27 UTC, ydnar approved these changes

2024-09-13 14:27 UTC, merged