feat: [Proposal] Move wasmimports/wasmexports to a dedicated file
bytecodealliance/wasm-tools-go pull request #194
Opened 2024-10-04 21:57 UTC by lxfontes

Move `wasmimport` and `wasmexport` declarations to a dedicated file (named as `extern` atm).
Add bindgen option `WithExternTag(string)`, which adds build tags to the extern file.

Rationale: The current `.wit.go` file carries Go and functions intended to be used as wasm bridge ( wasm import / export ).
Separating go code from wasm bridge allows readers to identify what is crossing the wasm boundary and gate them if needed. A secondary benefit is paving the way for `wit-bindgen-go` plugins that utilize the existing ABI and bridge into other implementations. The 2 that come to mind:
1. test/mocking for component unit testing ( with & without wasmtime )
2. networked protocols ( ex https://github.com/wrpc/wrpc )

Sample codegen for wasi:logging

logging.wit.go
```
//go:nosplit
func Log(level Level, context string, message string) {
	level0 := (uint32)(level)
	context0, context1 := cm.LowerString(context)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(context0), (uint32)(context1), (*uint8)(message0), (uint32)(message1))
	return
}
```

logging.extern.go
```
// Code generated by wit-bindgen-go. DO NOT EDIT.

package logging

// This file contains all wasmimport/wasmexport functions for "wasi:logging/logging".

//go:wasmimport wasi:logging/logging log
//go:noescape
func wasmimport_Log(level0 uint32, context0 *uint8, context1 uint32, message0 *uint8, message1 uint32)
```

Alternative: It is possible to use `linkname` in a similar manner, however I'm not sure if we can isolate cross-package dependencies with this approach as `wasmimport/export` bodies might need to bring in other packages for lifting/lowering types.

I'm not strong about the approach here if the alternative is preferred. Mostly looking for feedback & ideas about more ways to use the `cm` and codegen in the Go ecosystem.

2024-10-04 22:30 UTC, ydnar requested changes
This is great, thanks for drafting the PR. I support this direction.

2024-10-04 22:30 UTC, ydnar commented on cmd/wit-bindgen-go/cmd/generate/generate.go
> +		},
Let’s omit this. The build tags can be simple now: `//go:build wasm || wasm32 || tinygo.wasm`.

2024-10-04 22:30 UTC, ydnar commented on wit/bindgen/generator.go
> +	externFile := g.externFileFor(owner)
Let’s call this `wasmFileFor`.

2024-10-04 22:30 UTC, ydnar commented on wit/bindgen/generator.go
> +		stringio.Write(externFile, "type ", td.name, " ", g.typeDefRep(externFile, dir, t, td.name), "\n\n")
This type should be emitted in the main file, not the wasm file, so implementors don’t need to reimplement this type when compiling without `wasm` tag.

2024-10-04 22:30 UTC, ydnar commented on wit/bindgen/generator.go
> +func (g *generator) externFileFor(id wit.Ident) *gen.File {
`wasmFileFor`

2024-10-04 22:30 UTC, ydnar commented on wit/bindgen/generator.go
> +		stringio.Write(&b, "// This file contains all wasmimport/wasmexport functions for \"", id.String(), "\".\n\n")
```suggestion
		stringio.Write(&b, "// This file contains wasmimport and wasmexport declarations for \"", id.String(), "\".\n\n")
```

2024-10-04 22:30 UTC, ydnar commented on wit/bindgen/generator.go
> +		}
Let’s omit this configuration knob / CLI arg unless it’s absolutely necessary.

2024-10-04 22:30 UTC, ydnar commented on wit/bindgen/generator.go
> +	file.Trailer = "\n"
This should be unnecessary.

2024-10-05 03:10 UTC, ydnar commented
FYI, this project follows the Go project conventions for PR names and commit messages:

```
package: present tense verb describing change

More context...
```

2024-10-07 17:29 UTC, ydnar approved these changes
One minor change, we could do now or later.

2024-10-07 17:29 UTC, ydnar commented on wit/bindgen/generator.go
> +	wasmBuildTag = "wasm || wasm32 || tinygo.wasm"
This could probably be moved up beneath const `cmPackage` above.

2024-10-07 17:29 UTC, ydnar commented
Do you want to update the PR description to reflect current changes?

2024-10-08 20:51 UTC, lxfontes commented
> I checked out the branch and ran `go test ./wit/bindgen -write`, which writes all the generated Go to the filesystem. Afterward, I ran `go test ./...`, which fails because the `wasmimport` functions were no longer found.
> 
> I think it’s important that `go test ./...` on Go packages generated by `wit/bindgen` pass, or at the very least, _do not fail_.
> 
> If the wasm functions are sequestered in a .wasm.go file, how do you think we can accomplish this?

It's the `//go:build` gate on that file.
That's where the `wit-bindgen-go --wasmBuildTag` was helpful, but could also cause confusion.

I do agree that failing `go test` is a blocker and think we have 2 options:
- don't add the `//go:build` part to this PR
- duplicate wasm file, with a build tag negating the wasm file's tags

Duplicating the wasm file doesn't seem to add any value comparing to removing the build tag.
The follow-up PR I was planning is a mock generator for non-wasm builds, performing the lift/lowering into existing structs. That might be a better time to add the `//go:build` gate to wasm files.

Still have the build tag in the PR and can remove it if that makes sense 👍

2024-10-09 17:22 UTC, ydnar commented on wit/bindgen/testdata_test.go
> -		BuildFlags: []string{"-tags=wasm"},
Hah, nice.

2024-10-10 04:07 UTC, ydnar approved these changes

2024-10-10 04:08 UTC, merged

2024-10-10 05:33 UTC, ydnar commented
I should have rebased on `main` before merging, as the type alias PR uncovered a subtle bug in the code that generates Go representation of variant and result types.